# .github/workflows/deploy.yml
name: Deploy Bot to VPS
on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}
      - name: Copy files to VPS
        run: |
          rsync -av --exclude='.git*' ./ ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }}:/home/${{ secrets.VPS_USERNAME }}/telegram-pdf-tiff-bot/
      - name: Build & Restart (docker-compose)
        run: |
          ssh ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} 'cd telegram-pdf-tiff-bot && docker compose up -d --build'
