version: '3.8'

services:
  bot:
    build:
      context: .
    container_name: pdf_to_tiff_bot
    restart: always
    # Используем env_file для удобства и безопасности
    env_file:
      - .env
    volumes:
      - ./published_files:/app/published
      - ./temp:/app/temp
