services:
  bot:
    build: .
    container_name: pdf_to_tiff_bot
    restart: always
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
    # откройте порт, если бот работает как веб-сервер
    # ports:
    #   - "8080:8080"
    volumes:
      - ./temp:/app/temp
    # при необходимости добавьте другие переменные из секретов:
    # - ANOTHER_SECRET=${ANOTHER_SECRET}
