# docker-compose.yml
version: '3.9'

services:
  bot:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./logs:/bot/logs
      - ./tmp:/tmp/bot
      - /srv/files:/srv/files
    depends_on:
      - nginx
    network_mode: "host"
  nginx:
    image: nginx:latest
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /srv/files:/srv/files
    ports:
      - "80:80"
    restart: unless-stopped
