services:
  pdf_to_tiff_bot:
    build: .
    container_name: pdf_to_tiff_bot
    env_file:
      - .env
    restart: unless-stopped   # Авто-перезапуск (кроме ручной остановки)
    volumes:
      - ./published:/app/published
      - ./temp:/app/temp
    ports:
      - "8080:8080"
