services:
  bot:
    build: .
    container_name: pdf_to_tiff_bot
    restart: always
    environment:
      - BOT_TOKEN
      - PUBLIC_BASE_URL=https://yourdomain.com
      - PUBLISH_DIR=/app/published
      - TMP_DIR=/app/temp
      - MAX_FILE_MB=100
      - GS_PATH=/usr/bin/gs
      - DPI_DEFAULT=96
      - CONCURRENCY=2
    volumes:
      - ./temp:/app/temp
